<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>R: Throws an exception</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="R.css" />
</head><body>

<table width="100%" summary="page for throw {R.methodsS3}"><tr><td>throw {R.methodsS3}</td><td style="text-align: right;">R Documentation</td></tr></table>

<h2>Throws an exception</h2>

<h3>Description</h3>

<p>Throws an exception by calling stop().
</p>
<p>Note that <code>throw()</code> can be defined for specific classes, which can
then be caught (or not) using <code><a href="../../base/html/conditions.html">tryCatch</a></code>().
</p>
<p><em>This default function will be overridden by ditto in the <span class="pkg">R.oo</span>
package, if that is loaded.  The latter <code><a href="../../R.oo/html/throw.html">throw</a></code> implementation
is fully backward compatible with this one, but the error object thrown
is of class <code><a href="../../R.oo/html/Exception.html">Exception</a></code>.</em>
</p>


<h3>Usage</h3>

<pre>
## Default S3 method:
throw(...)
</pre>


<h3>Arguments</h3>

<table summary="R argblock">
<tr valign="top"><td><code>...</code></td>
<td>
<p>One or several strings that are concatenated and collapsed
into on message string.</p>
</td></tr>
</table>


<h3>Value</h3>

<p>Returns nothing.
</p>


<h3>Author(s)</h3>

<p>Henrik Bengtsson</p>


<h3>Examples</h3>

<pre>
rbern &lt;- function(n=1, prob=1/2) {
  if (prob &lt; 0 || prob &gt; 1)
    throw("Argument 'prob' is out of range: ", prob)
  rbinom(n=n, size=1, prob=prob)
}

rbern(10, 0.4)
# [1] 0 1 0 0 0 1 0 0 1 0
tryCatch({
  rbern(10, 10*0.4)
}, error=function(ex) {})
</pre>

<hr /><div style="text-align: center;">[Package <em>R.methodsS3</em> version 1.7.1 <a href="00Index.html">Index</a>]</div>
</body></html>
